services:
  # The web container is an instance of exactly the same Docker image as your
  # Cloud application container.
  web:
    build: "."
    container_name: wbi-web
    links:
      - "db:postgres"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    # Change the port if you'd like to expose your project locally on a
    # different port, for example if you already use port 8000 for
    # something else.
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    # The default command that the container starts with. If you'd like to run
    # the project locally in Live configuration, you will need to change this.
    # See https://docs.divio.com/en/latest/how-to/local-in-live-mode.html.
    command: python manage.py runserver 0.0.0.0:80
    # Add any environment variables your project needs to the .env-local file.
    # See https://docs.divio.com/en/latest/reference/configuration-environment-variables.html.
    env_file: .env-local

  # On the Cloud, your database runs on a dedicated cluster. Locally, we
  # replicate it in a Docker container called "db".
  db:
    image: postgres:15.3-alpine
    container_name: wbi-db
    environment:
      POSTGRES_USER: "wbi"
      POSTGRES_DB: "db_wbi"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGUSER: "wbi"
      PGDATABASE: "db_wbi"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local